services:
  db:
    image: postgres:17-alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles:
      - dev

  app-dev:
    container_name: nest-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    profiles:
      - dev

  app-prod:
    container_name: nest-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.production
    ports:
      - 3000:3000
    profiles:
      - prod

volumes:
  db-data:
